### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by xdraylin** [JF002/cfGUI#2]
I would like to kindly ask you to add a license to your project. As it is now, neither personal nor commercial use of your code is permitted withouth potential legal issues.

Thank you!

**Comment by JF002** [comment]
Indeed, I did not choose any license for the project. It's a tough choice...
Do you have any need for a specific license in mind?

**Comment by xdraylin** [comment]
Well, of course I would prefer an MIT License as it is very permissive and very common amongst popular Arduino / Platform.io libraries.

Another common license is LGPL which is a bit more restrictive to (at least in theory) encourage pushing library changes ustream. This is a great license for libraries which can be dynamically linked, but kind of a hassle to deal with on micro-processors where everything is liked into a single blob.

But in the end it depends on your personal preferences which license you choose.

**Comment by JF002** [comment]
Thanks for these useful informations!
Yeah, from what I read, LGPL seemed good, but yeah, there is no dynamic linking in Arduino...
I'll need some time to study the licence, but MIT looks good.

**Comment by JF002** [comment]
Done ! I've finally chosen the MIT license ;)
